project_name: single_shell # project name for logging using wandb (wandb.ai), uncomment in main.py

model_name: fod # see models.py
output_calculator: singleshell # see output_calculators.py
loss_function_name: singleshell_csd_loss # see loss_functions.py
gaussian_encoding: True # use fourier features encoding
fod_rescale: True # multiply with rescaling factor after convolution of FOD and response
dataset_name: singleshell # see datasets.py
bval_delta: 100 # values between the shell defined below +- bval_delta are included for the shell
shells: [3000] # which bval shell to use
scale_data: True # scale the dwi to 0-1 range before fitting
scheduler: True # use a learning rate schedular

width: 145
height: 174
depth: 145

log_freq: 0 # number of iterations between logging, 0 for no logging

paths: # from repository root
  mask: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_diff_mask.nii.gz
  fsl_bvecs: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_fsl.bvec
  fsl_bvals: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_fsl.bval
  response: /data/users/cyang/HCP-MWU-ODF/mwu100408/csd/mwu100408_rf_wm.txt
  nifti: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_diff.nii.gz
  recon_nifti: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_diff.nii.gz
  recon_mask: /data/users/cyang/HCP-MWU-ODF/mwu100408/diff/mwu100408_diff_mask.nii.gz
  output: runs/mwu100408

train_cfg:
  lmax: 8
  lpos: 5000 # number of positional encodings
  n_layers: 4
  hidden_dim: 1024
  lr: 0.0001
  epochs: 30
  batch_size: 500
  lambda: 0 # deprecated, but necessary to put to a value
  slice_id: 45 # slice used for logging intermediate images
  sigma: 4 # sigma for gaussian used in fourier features encoding
